version: '3.8'
services:
  app:
    build:
      context: ./
      target: runner
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
