name: PR Check

on: [pull_request]

jobs:
  linting-building-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install && npm i @next/swc-linux-x64-gnu
      - name: Build App
        run: npm run build
